# Generated by Django 5.0.2 on 2024-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='transcript',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
